<a href="https://colab.research.google.com/github/harries0306/Pratice/blob/master/NN_basic_without_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
import numpy as np

In [107]:
AND=pd.DataFrame({'x1':(0,0,1,1),'x2':(0,1,0,1),'y':(0,0,0,1)})

In [108]:
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [109]:
w=np.random.randn(3)*1e-4
w

array([ 7.37183381e-05, -1.73629580e-04,  8.50937272e-05])

In [110]:
g=lambda inputs,weights : np.where(np.dot(inputs,weights)>0,1,0)

In [111]:
#creating a function for NN:
def NN(inputs,weights,n_iterations,targets,eta):
  #creating bias for each row in input

  inputs=np.c_[inputs,-np.ones(len(inputs))]
  for i in range((n_iterations)):

    #print('inputs'+str(inputs))
    #print(weights)
    
    activations=g(inputs,weights)
    
    #print(activations)
    #back propogation
    
    weights -= eta*np.dot(np.transpose(inputs),(activations-targets))
  return(weights)
    

In [112]:
inputs=AND[['x1','x2']]
targets=AND['y']
w=NN(inputs,w,3,targets,0.25)
w

array([0.25007372, 0.24982637, 0.25008509])

In [113]:
g(np.c_[inputs, -np.ones((len(inputs), 1))], w)

array([0, 0, 0, 1])